name: Outlayman
favicon: null
layout_spectrum: 0.4804462876636535
typography_spectrum: 0.3107189384754747
title: Online Payment System
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8240776404272765
  lightness: 0.2476170181762427
  saturation: 0.7044242350384593
  rhythmicContrast: 0.9721926525235176
purpose: []
