name: Outlayman
favicon: null
layout_spectrum: 1
typography_spectrum: 0.3107189384754747
title: Outlayman
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74287705-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.3125
  lightness: 0.4375
  saturation: 0.4375
  rhythmicContrast: 0.25
purpose: []
